"use client"

import React from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, ShieldCheck } from "lucide-react";
import { SectionTitle, Subtitle, Paragraph, FormulaBox, ListItem } from "./about-shared-elements";

export const SarDijkstraDetails = () => {
  return (
    <>
      <SectionTitle>The SAR-Dijkstra Algorithm</SectionTitle>

      <Card className="mb-12 bg-card/80 backdrop-blur-lg shadow-xl border-border/30">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center"><Brain className="mr-3 h-7 w-7 text-sky-500" />Core Concept</CardTitle>
        </CardHeader>
        <CardContent>
          <Paragraph>
            The SAR-Dijkstra algorithm is an extension of the classic Dijkstra's algorithm. While Dijkstra's algorithm finds the shortest path based on a single cost metric (e.g., distance or latency), SAR-Dijkstra utilizes a composite cost function that integrates multiple security and performance parameters. This allows for a more holistic assessment of network paths, balancing security considerations with traditional routing objectives.
          </Paragraph>
          <Paragraph>
            The algorithm iteratively explores network nodes, calculating the cumulative 'security-aware cost' to reach each node from a source. It maintains a set of unvisited nodes and, at each step, selects the unvisited node with the lowest cumulative security-aware cost. This process continues until the destination node is reached or all reachable nodes have been visited.
          </Paragraph>
        </CardContent>
      </Card>

      <FormulaBox title="The SAR-Dijkstra Cost Function">
        <React.Fragment>
          {/* Main Formula */}
          <div className="bg-muted/50 dark:bg-muted/30 p-6 rounded-lg mb-8 text-center border border-border">
            <div className="text-2xl mb-4 text-foreground">
              <span className="font-bold">PathCost</span>
              <sub className="text-lg">SAR</sub>
              <span className="mx-4">=</span>
              <span className="text-3xl">∑</span>
              <sub className="text-sm ml-1">e∈Path</sub>
              <span className="ml-4">[α · c(e) + β · s(e)]</span>
            </div>
          </div>

          {/* Formula Components */}
          <div className="space-y-6 mb-8">
            <h3 className="text-2xl font-bold border-b-2 border-border pb-2 text-foreground">Formula Components</h3>
            <div className="grid gap-4">
              <div className="bg-blue-50 dark:bg-blue-950/30 p-4 rounded-lg border border-blue-200 dark:border-blue-800">
                <h4 className="text-lg font-bold text-blue-800 dark:text-blue-300 mb-2">PathCost<sub>SAR</sub></h4>
                <p className="text-foreground/80">The total composite cost of a network path, combining both traditional routing metrics and security considerations.</p>
              </div>

              <div className="bg-green-50 dark:bg-green-950/30 p-4 rounded-lg border border-green-200 dark:border-green-800">
                <h4 className="text-lg font-bold text-green-800 dark:text-green-300 mb-2">∑<sub>e∈Path</sub></h4>
                <p className="text-foreground/80">Summation over all edges (e) in the selected path. Each edge represents a network path segment.</p>
              </div>

              <div className="bg-orange-50 dark:bg-orange-950/30 p-4 rounded-lg border border-orange-200 dark:border-orange-800">
                <h4 className="text-lg font-bold text-orange-800 dark:text-orange-300 mb-2">c(e) - Cost Function</h4>
                <p className="text-foreground/80">Traditional routing metrics for edge e, including:</p>
                <ul className="list-disc list-inside mt-2 ml-4 text-muted-foreground">
                  <li>Network latency</li>
                  <li>Bandwidth usage</li>
                  <li>Hop count</li>
                </ul>
              </div>

              <div className="bg-red-50 dark:bg-red-950/30 p-4 rounded-lg border border-red-200 dark:border-red-800">
                <h4 className="text-lg font-bold text-red-800 dark:text-red-300 mb-2">s(e) - Security Risk</h4>
                <p className="text-foreground/80">Numerical score representing vulnerability level or probability of attack for edge e.</p>
                <p className="text-sm text-red-600 dark:text-red-400 mt-2 italic">Dynamically generated by Machine Learning Pipeline</p>
              </div>
            </div>
          </div>

          {/* Weighting Factors */}
          <div className="space-y-4 mb-8">
            <h3 className="text-2xl font-bold border-b-2 border-border pb-2 text-foreground">Weighting Factors</h3>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-purple-50 dark:bg-purple-950/30 p-4 rounded-lg border border-purple-200 dark:border-purple-800">
                <h4 className="text-lg font-bold text-purple-800 dark:text-purple-300 mb-2">α (Alpha)</h4>
                <p className="text-foreground/80 mb-2">Tunable weighting factor for cost function</p>
                <div className="bg-card dark:bg-card/50 p-3 rounded border-l-4 border-purple-400 dark:border-purple-500">
                  <p className="text-sm text-foreground"><strong>Higher α:</strong> Prioritizes shorter/faster paths (lower cost)</p>
                </div>
              </div>

              <div className="bg-indigo-50 dark:bg-indigo-950/30 p-4 rounded-lg border border-indigo-200 dark:border-indigo-800">
                <h4 className="text-lg font-bold text-indigo-800 dark:text-indigo-300 mb-2">β (Beta)</h4>
                <p className="text-foreground/80 mb-2">Tunable weighting factor for security risk</p>
                <div className="bg-card dark:bg-card/50 p-3 rounded border-l-4 border-indigo-400 dark:border-indigo-500">
                  <p className="text-sm text-foreground"><strong>Higher β:</strong> Prioritizes safer paths (lower security risk)</p>
                </div>
              </div>
            </div>
          </div>
        </React.Fragment>
      </FormulaBox>

      <Card className="mb-12 bg-card/80 backdrop-blur-lg shadow-xl border-border/30">
        <CardHeader>
          <CardTitle className="text-2xl flex items-center"><ShieldCheck className="mr-3 h-7 w-7 text-sky-500" />Components of the Cost Function</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            {/* Performance Cost (c(e)) Section */}
            <div className="bg-orange-50 dark:bg-orange-950/30 p-4 rounded-lg border border-orange-200 dark:border-orange-800">
              <h4 className="text-lg font-bold text-orange-800 dark:text-orange-300 mb-2">1. Performance Cost (<code>c(e)</code>)</h4>
              <p className="text-foreground/80 mb-3">
                This component quantifies traditional network performance metrics. It could be derived from:
              </p>
              <ul className="list-disc list-inside mt-2 ml-4 text-muted-foreground">
                <ListItem><strong>Latency:</strong> Delay in data transmission over the link.</ListItem>
                <ListItem><strong>Bandwidth:</strong> Data carrying capacity of the link. (Often, higher bandwidth means lower cost).</ListItem>
                <ListItem><strong>Hop Count:</strong> Number of intermediate devices (can be implicitly part of path accumulation).</ListItem>
              </ul>
              <p className="text-foreground/80 mt-3">
                These values are typically normalized (e.g., scaled to a range of 0 to 1) to ensure they can be meaningfully combined with security metrics.
              </p>
            </div>

            {/* Security Cost (s(e)) Section */}
            <div className="bg-red-50 dark:bg-red-950/30 p-4 rounded-lg border border-red-200 dark:border-red-800">
              <h4 className="text-lg font-bold text-red-800 dark:text-red-300 mb-2">2. Security Cost (<code>s(e)</code>)</h4>
              <p className="text-foreground/80 mb-3">
                This is the core of the security-aware aspect. It can be a composite of several factors, potentially derived from advanced analytics like Machine Learning (as detailed below) or by considering the following elements:
              </p>
              
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: 0.35 }}
                className="my-4 p-4 bg-card dark:bg-card/50 rounded-lg border border-border shadow-sm"
              >
                <h4 className="text-md font-semibold text-foreground mb-3 flex items-center">
                  <Brain className="mr-2 h-5 w-5 text-sky-500" /> ML-Powered Security Risk Scoring
                </h4>
                <p className="text-sm text-foreground/80 mb-2">
                  A significant approach to determining security cost involves using a Machine Learning (ML) model. This model is trained to predict Security Risk Scores (s(e)) for network edges (links) or flows. The prediction is based on a variety of traffic characteristics and potentially historical data, as outlined in the research.
                </p>
                <p className="text-sm text-foreground/80 mb-2">
                  The input features for such an ML model typically include:
                </p>
                <ul className="list-disc list-inside text-sm text-muted-foreground ml-4">
                  <ListItem>L4 Source Port (<code>L4_SRC_PORT</code>)</ListItem>
                  <ListItem>L4 Destination Port (<code>L4_DST_PORT</code>)</ListItem>
                  <ListItem>L4 Protocol (<code>PROTOCOL</code>), e.g., TCP, UDP</ListItem>
                  <ListItem>L7 Protocol ID (<code>L7_PROTO</code>), e.g., HTTP, DNS</ListItem>
                  <ListItem>Bytes from Destination to Source (<code>IN_BYTES</code>)</ListItem>
                  <ListItem>Bytes from Source to Destination (<code>OUT_BYTES</code>)</ListItem>
                  <ListItem>Packets from Destination to Source (<code>IN_PKTS</code>)</ListItem>
                  <ListItem>Packets from Source to Destination (<code>OUT_PKTS</code>)</ListItem>
                  <ListItem>TCP Flags (<code>TCP_FLAGS</code>), e.g., SYN, ACK</ListItem>
                  <ListItem>Flow Duration in Milliseconds (<code>FLOW_DURATION_MILLISECONDS</code>)</ListItem>
                </ul>
              </motion.div>

              <p className="text-foreground/80 mb-3 mt-4">Other factors contributing to Security Cost can include:</p>
              <ul className="list-disc list-inside mt-2 ml-4 text-muted-foreground">
                <ListItem><strong>Node Trustworthiness:</strong> A score indicating the reliability and security posture of nodes <code>u</code> and <code>v</code>. This might be based on historical behavior, patching levels, or security audits.</ListItem>
                <ListItem><strong>Link Vulnerability:</strong> Assesses the susceptibility of the physical or logical link to attacks (e.g., likelihood of eavesdropping, jamming).</ListItem>
                <ListItem><strong>Threat Exposure:</strong> Considers the current threat intelligence related to the path or nodes involved. For instance, a path transiting through a region known for high cyber-attack activity might incur a higher security cost.</ListItem>
                <ListItem><strong>Encryption Strength:</strong> Links using stronger encryption protocols might have lower security costs.</ListItem>
                <ListItem><strong>Intrusion Detection System (IDS) Feedback:</strong> Alerts or risk scores from an IDS monitoring the link or adjacent nodes can dynamically influence this cost.</ListItem>
              </ul>
              <p className="text-foreground/80 mt-3">
                Similar to performance metrics, security factors are normalized. A higher security cost generally indicates a less secure or riskier link.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </>
  );
};
